"""Paradise Stack - Unified Runner
Orchestrates Planner -> Builder -> Guardian pipeline.
"""

import sys
import json
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))

class ParadiseRunner:
    """Main orchestrator for Paradise Stack."""
    
    def __init__(self):
        self.output_dir = PROJECT_ROOT / "outputs"
        self.output_dir.mkdir(exist_ok=True)
        
    def run(self, task, language="python"):
        """Run full pipeline: Plan -> Build -> Guardian."""
        wf_id = f"wf_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        wf_dir = self.output_dir / wf_id
        wf_dir.mkdir(exist_ok=True)
        
        manifest = {
            "workflow_id": wf_id,
            "task": task,
            "language": language,
            "phases": {},
            "status": "running",
            "created_at": datetime.now().isoformat(),
            "deliverables": []
        }
        
        # Phase 1: Plan
        print(f"\n[1/3] PLANNER: Analyzing '{task}'...")
        plan = self._plan(task, language)
        manifest["phases"]["plan"] = plan
        
        # Phase 2: Build
        print("\n[2/3] BUILDER: Generating code...")
        code = self._build(task, language)
        manifest["phases"]["build"] = {"files": len(code)}
        
        # Phase 3: Guardian
        print("\n[3/3] GUARDIAN: Verifying...")
        verification = self._verify(code, language)
        manifest["phases"]["guardian"] = verification
        
        # Save deliverables
        for fname, content in code.items():
            fpath = wf_dir / fname
            fpath.write_text(content, encoding='utf-8')
            manifest["deliverables"].append({
                "id": fname,
                "name": fname,
                "path": str(fpath),
                "size": fpath.stat().st_size
            })
        
        manifest["status"] = "completed"
        manifest["completed_at"] = datetime.now().isoformat()
        
        with open(wf_dir / "manifest.json", 'w') as f:
            json.dump(manifest, f, indent=2)
        
        print(f"\n{'='*50}")
        print(f"DONE: {wf_id}")
        print(f"Files: {[d['name'] for d in manifest['deliverables']]}")
        print(f"Output: {wf_dir}")
        
        return manifest
    
    def _plan(self, task, language):
        """Plan phase - analyze and design."""
        return {
            "language": language,
            "approach": "generate",
            "steps": ["analyze", "generate", "verify"]
        }
    
    def _build(self, task, language):
        """Build phase - generate code."""
        templates = {
            "python": {
                "main.py": f'''"""Paradise Stack Generated
Task: {task}
"""
from pathlib import Path

def main():
    print("Paradise Stack Output")
    print(f"Task: {task}")
    # TODO: Implement {task}
    return 0

if __name__ == "__main__":
    main()
''',
                "README.md": f"# Generated by Paradise Stack\n\nTask: {task}\n"
            },
            "javascript": {
                "main.js": f'''// Paradise Stack Generated
// Task: {task}
console.log("Paradise Stack Output");
console.log("Task: {task}");
// TODO: Implement {task}
''',
                "package.json": '{"name": "paradise-output", "version": "1.0.0"}'
            }
        }
        return templates.get(language, {"output.txt": f"Task: {task}\n"})
    
    def _verify(self, code, language):
        """Guardian phase - verify code."""
        issues = []
        
        for fname, content in code.items():
            if len(content) < 10:
                issues.append(f"{fname}: too short")
        
        return {
            "passed": len(issues) == 0,
            "issues": issues
        }

def main():
    if len(sys.argv) > 1:
        task = " ".join(sys.argv[1:])
    else:
        task = "Create a hello world program"
    
    runner = ParadiseRunner()
    runner.run(task)

if __name__ == "__main__":
    main()
