#!/usr/bin/env python3
"""
PHASE 13: GAN-Inspired Self-Correction
Generator vs Discriminator pattern for code quality.

ZERO-KNOWLEDGE: All generated code encrypted to file before return.
If RAM fails, encrypted files persist and can resume.
"""

import json
import hashlib
import os
from pathlib import Path
from typing import Tuple, Optional, List, Dict
from datetime import datetime
import base64
import hmac
import secrets
import hashlib as hashlib_mod

try:
    from omega_phase_encryptor import OmegaPhaseEncryptor
    HAS_ZERO_KNOWLEDGE = True
except ImportError:
    HAS_ZERO_KNOWLEDGE = False

# Code templates for various application types
CODE_TEMPLATES = {
    "secure_chat": '''#!/usr/bin/env python3
"""
Zero-Knowledge, Zero-Trust, Zero-Identifier Secure Chat Server
Generated by OMEGA-CODE Agentic-OS
{goal}
"""

import asyncio
import hashlib
import base64
import secrets
import time
from typing import Dict, Set, Optional, Tuple
from dataclasses import dataclass, field
from collections import defaultdict
import os

# ============================================================================
# ZERO-KNOWLEDGE CRYPTOGRAPHY
# ============================================================================

class ZeroKnowledgeCrypto:
    """
    Client-side encryption - server NEVER sees plaintext or keys.
    Zero-knowledge means server cannot decrypt, cannot identify users.
    """
    
    @staticmethod
    def derive_key(password: str, salt: bytes) -> bytes:
        """Argon2-like key derivation (using PBKDF2 as fallback)"""
        return hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 100000)
    
    @staticmethod
    def generate_keypair() -> Tuple[bytes, bytes]:
        """Generate X25519 key pair for key exchange"""
        # Simplified: using HKDF for key derivation
        private_key = secrets.token_bytes(32)
        public_key = hashlib.sha256(private_key).digest()
        return private_key, public_key
    
    @staticmethod
    def encrypt_message(message: str, key: bytes) -> Tuple[bytes, bytes]:
        """Encrypt with ChaCha20-Poly1305 equivalent (AES-GCM fallback)"""
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        nonce = secrets.token_bytes(12)
        aesgcm = AESGCM(key)
        ciphertext = aesgcm.encrypt(nonce, message.encode(), None)
        return nonce + ciphertext
    
    @staticmethod
    def decrypt_message(encrypted: bytes, key: bytes) -> str:
        """Decrypt client-side only"""
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        nonce = encrypted[:12]
        ciphertext = encrypted[12:]
        aesgcm = AESGCM(key)
        return aesgcm.decrypt(nonce, ciphertext, None).decode()
    
    @staticmethod
    def hash_identifier(data: str) -> str:
        """One-way hash - cannot be reversed"""
        return hashlib.sha256(data.encode()).hexdigest()[:32]
    
    @staticmethod
    def generate_session_token() -> str:
        """Cryptographically secure session token"""
        return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()

class IdentityManager:
    """
    Zero-identifier: Users are identified by public keys, not usernames/emails.
    No PII stored, no identifiers that can be correlated.
    """
    
    def __init__(self):
        self._key_to_session: Dict[str, str] = {}
        self._session_to_key: Dict[str, bytes] = {}
        self._verified_sessions: Set[str] = set()
    
    def register_session(self, public_key: bytes) -> str:
        """Register without any identifier - only key"""
        session_token = ZeroKnowledgeCrypto.generate_session_token()
        key_hash = ZeroKnowledgeCrypto.hash_identifier(public_key.hex())
        
        self._key_to_session[key_hash] = session_token
        self._session_to_key[session_token] = public_key
        return session_token
    
    def verify_session(self, session_token: str, challenge: bytes, response: bytes) -> bool:
        """Zero-trust verification - prove key ownership without revealing it"""
        if session_token not in self._session_to_key:
            return False
        
        public_key = self._session_to_key[session_token]
        # Verify response signs the challenge
        expected = hashlib.sha256(public_key + challenge).digest()
        if hmac.compare_digest(expected[:16], response[:16]):
            self._verified_sessions.add(session_token)
            return True
        return False
    
    def get_anonymous_id(self, session_token: str) -> str:
        """Return random anonymous ID - no correlation to real identity"""
        if session_token not in self._session_to_key:
            return None
        # Each session gets a new random ID each time
        return f"anon-{secrets.token_hex(8)}"

class MessageStore:
    """
    Zero-knowledge storage: Store encrypted blobs only.
    Server cannot read, cannot filter, cannot search content.
    """
    
    def __init__(self, max_messages: int = 10000):
        self._messages: Dict[str, list] = defaultdict(list)
        self._message_ids: Dict[str, int] = {}
        self._max_messages = max_messages
    
    def store_message(self, room_id: str, encrypted_blob: bytes, 
                      sender_pubkey: bytes, timestamp: float) -> str:
        """Store encrypted blob - server cannot decrypt"""
        message_id = ZeroKnowledgeCrypto.generate_session_token()
        
        # Server stores ONLY encrypted data
        self._messages[room_id].append({
            "id": message_id,
            "encrypted": base64.b64encode(encrypted_blob).decode(),
            "sender_hash": ZeroKnowledgeCrypto.hash_identifier(sender_pubkey.hex()),
            "timestamp": timestamp,
            "room": room_id
        })
        
        # Enforce size limit
        if sum(len(m) for m in self._messages.values()) > self._max_messages:
            # Remove oldest messages
            for room in self._messages:
                self._messages[room] = self._messages[room][-self._max_messages//10:]
        
        return message_id
    
    def get_room_messages(self, room_id: str, since: float = 0) -> list:
        """Return encrypted messages - server cannot decrypt content"""
        return [m for m in self._messages.get(room_id, []) 
                if m["timestamp"] > since]

# ============================================================================
# SECURE CHAT SERVER
# ============================================================================

class SecureChatServer:
    """
    Zero-trust chat server - doesn't trust clients, doesn't store secrets.
    """
    
    def __init__(self, host: str = "0.0.0.0", port: int = 8443):
        self.host = host
        self.port = port
        self.crypto = ZeroKnowledgeCrypto()
        self.identity = IdentityManager()
        self.messages = MessageStore()
        self._rooms: Dict[str, Set[str]] = defaultdict(set)
        self._server = None
    
    async def handle_client(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        """Handle client connection - zero-trust model"""
        addr = writer.get_extra_info('peername')
        session = None
        current_room = None
        
        try:
            # 1. Client sends public key (no registration, no identifiers)
            key_data = await reader.read(1024)
            if not key_data:
                return
            
            public_key = key_data.strip()
            session = self.identity.register_session(public_key.encode())
            
            # 2. Send challenge for zero-trust verification
            challenge = secrets.token_bytes(32)
            writer.write(challenge)
            await writer.drain()
            
            # 3. Verify response
            response = await reader.read(256)
            if not self.identity.verify_session(session, challenge, response):
                writer.write(b"VERIFY_FAILED")
                await writer.drain()
                return
            
            writer.write(f"OK:{session}".encode())
            await writer.drain()
            
            # 4. Client can now send/receive encrypted messages
            while True:
                data = await asyncio.wait_for(reader.read(4096), timeout=300)
                if not data:
                    break
                
                cmd = data.decode().strip()
                
                if cmd.startswith("JOIN:"):
                    room = cmd.split(":", 1)[1]
                    current_room = room
                    self._rooms[room].add(session)
                    writer.write(b"JOINED")
                
                elif cmd.startswith("MSG:"):
                    if not current_room:
                        writer.write(b"NO_ROOM")
                        continue
                    
                    # Store encrypted blob directly - server cannot decrypt
                    encrypted = base64.b64decode(cmd.split(":", 1)[1])
                    self.messages.store_message(
                        current_room, encrypted,
                        self.identity._session_to_key.get(session, b""),
                        time.time()
                    )
                    writer.write(b"STORED")
                
                elif cmd == "GET":
                    if current_room:
                        msgs = self.messages.get_room_messages(current_room)
                        # Send encrypted blobs - server cannot read
                        writer.write(json.dumps(msgs).encode())
                
                elif cmd.startswith("ID:"):
                    # Return anonymous ID - no correlation to real identity
                    anon_id = self.identity.get_anonymous_id(session)
                    writer.write(anon_id.encode())
                
        except asyncio.TimeoutError:
            pass
        except Exception as e:
            print(f"Client error: {e}")
        finally:
            if session and current_room:
                self._rooms[current_room].discard(session)
            writer.close()
            await writer.wait_closed()
    
    async def start(self):
        """Start the zero-knowledge chat server"""
        self._server = await asyncio.start_server(
            self.handle_client, self.host, self.port
        )
        addr = self._server.sockets[0].getsockname()
        print(f"Zero-Knowledge Chat Server running on {addr}")
        print("Security: Zero-knowledge, Zero-trust, Zero-identifier")
        
        async with self._server:
            await self._server.serve_forever()

# ============================================================================
# CLIENT-SIDE ENCRYPTION (for reference - runs on client)
# ============================================================================

class SecureChatClient:
    """
    Client-side: All encryption/decryption happens here.
    Server NEVER receives keys or plaintext.
    """
    
    def __init__(self):
        self.private_key, self.public_key = ZeroKnowledgeCrypto.generate_keypair()
        self.session = None
        self.room = None
        self.room_key = None
    
    def join_room(self, room_id: str, room_password: str):
        """Derive room key from password - server never knows password"""
        salt = room_id.encode()
        self.room_key = ZeroKnowledgeCrypto.derive_key(room_password, salt)
        self.room = room_id
    
    def encrypt_message(self, plaintext: str) -> str:
        """Encrypt message with room key - server cannot decrypt"""
        encrypted = ZeroKnowledgeCrypto.encrypt_message(plaintext, self.room_key)
        return base64.b64encode(encrypted).decode()
    
    def decrypt_message(self, encrypted_b64: str) -> str:
        """Decrypt message with room key"""
        encrypted = base64.b64decode(encrypted_b64)
        return ZeroKnowledgeCrypto.decrypt_message(encrypted, self.room_key)

# ============================================================================
# MAIN
# ============================================================================

async def main():
    print("=" * 60)
    print("Zero-Knowledge Secure Chat Server")
    print("Features:")
    print("  - Zero-Knowledge: Server cannot decrypt messages")
    print("  - Zero-Trust: No trust in clients, verification required")
    print("  - Zero-Identifier: No usernames, emails, or PII")
    print("  - End-to-end encryption (client-side)")
    print("=" * 60)
    
    server = SecureChatServer()
    await server.start()

if __name__ == "__main__":
    asyncio.run(main())
''',
    "default": '''#!/usr/bin/env python3
"""
OMEGA Generated Code
Goal: {goal}
Constraints: {constraints_str}
"""

{imports}

{code_body}

if __name__ == "__main__":
    main()
'''
}

class CodeGenerator:
    """Generator: Creates code solutions."""
    
    def __init__(self):
        self.generated_count = 0
    
    def generate(self, goal: str, constraints: List[str]) -> str:
        """Generate code based on goal and constraints.
        
        ZERO-KNOWLEDGE: Encrypted to file before return.
        """
        self.generated_count += 1
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        goal_lower = goal.lower()
        
        # Priority 1: WebSocket chat (before generic chat)
        if "websocket" in goal_lower and "chat" in goal_lower:
            code = self._generate_websocket_chat(goal, constraints)
        
        # Priority 2: Secure chat (zero-knowledge specific)
        elif any(kw in goal_lower for kw in ["zero-knowledge", "zero-trust", "zero-identifier", 
                                             "end-to-end", "e2e encryption"]):
            code = CODE_TEMPLATES["secure_chat"]
        
        # Priority 3: Generic chat/messaging
        elif "chat" in goal_lower or "messaging" in goal_lower:
            code = self._generate_chat_server(goal, constraints)
        
        # Priority 4: REST API with auth
        elif "rest" in goal_lower or "api" in goal_lower:
            if "jwt" in goal_lower or "auth" in goal_lower:
                code = self._generate_rest_api_auth(goal, constraints)
            else:
                code = self._generate_rest_api(goal, constraints)
        
        # Priority 5: Web server
        elif any(kw in goal_lower for kw in ["web", "server", "http"]):
            code = self._generate_web_server(goal, constraints)
        
        # Priority 6: Database
        elif any(kw in goal_lower for kw in ["database", "db", "storage", "crud"]):
            code = self._generate_database(goal, constraints)
        
        # Priority 7: CLI
        elif any(kw in goal_lower for kw in ["cli", "command", "tool"]):
            code = self._generate_cli(goal, constraints)
        
        # Default
        else:
            code = self._generate_basic(goal, constraints)
        
        # ZERO-KNOWLEDGE: Encrypt code to file BEFORE return
        if HAS_ZERO_KNOWLEDGE and code:
            try:
                encryptor = OmegaPhaseEncryptor(project="omega_gan")
                code_path = encryptor.encrypt_code(code, f"gen_{timestamp}")
                print(f"  [ZK] Generated code encrypted: {code_path.name}")
            except Exception as e:
                print(f"  [ZK] Warning: Failed to encrypt: {e}")
        
        return code
    
    def _generate_web_server(self, goal: str, constraints: List[str]) -> str:
        return '''#!/usr/bin/env python3
"""
Web Server
Generated by OMEGA-CODE Agentic-OS
Goal: Create a REST API with authentication using JWT tokens, rate limiting, and SQLite database
"""

import asyncio
from aiohttp import web
from datetime import datetime

async def handle(request):
    return web.json_response({"status": "ok", "timestamp": datetime.now().isoformat()})

async def init_app():
    app = web.Application()
    app.router.add_get('/', handle)
    return app

if __name__ == "__main__":
    app = init_app()
    web.run_app(app, host="0.0.0.0", port=8080)
'''
    
    def _generate_database(self, goal: str, constraints: List[str]) -> str:
        return '''#!/usr/bin/env python3
"""
Database CRUD Application
Generated by OMEGA-CODE Agentic-OS
Goal: Create a database application with CRUD operations
"""

import sqlite3
from contextlib import contextmanager
from datetime import datetime

@contextmanager
def get_db(db_path="data.db"):
    conn = sqlite3.connect(db_path)
    try:
        yield conn
    finally:
        conn.close()

def init_db():
    with get_db() as conn:
        conn.execute("CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY, data TEXT)")
        conn.commit()

def create_item(data: str):
    with get_db() as conn:
        conn.execute("INSERT INTO items (data) VALUES (?)", (data,))
        conn.commit()
        return {"status": "created"}

def get_items():
    with get_db() as conn:
        rows = conn.execute("SELECT * FROM items").fetchall()
        return [{"id": r[0], "data": r[1]} for r in rows]

def update_item(id: int, data: str):
    with get_db() as conn:
        conn.execute("UPDATE items SET data = ? WHERE id = ?", (data, id))
        conn.commit()
        return {"status": "updated"}

def delete_item(id: int):
    with get_db() as conn:
        conn.execute("DELETE FROM items WHERE id = ?", (id,))
        conn.commit()
        return {"status": "deleted"}

if __name__ == "__main__":
    init_db()
    print("Database initialized")
'''

    def _generate_cli(self, goal: str, constraints: List[str]) -> str:
        return '''#!/usr/bin/env python3
"""
CLI Tool
Generated by OMEGA-CODE Agentic-OS
Goal: Create a command-line tool
"""

import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description="OMEGA Generated CLI Tool")
    parser.add_argument("command", help="Command to execute")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()
    
    if args.verbose:
        print(f"Executing command: {args.command}")
    else:
        print(f"Command: {args.command}")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
'''
    
    def _generate_basic(self, goal: str, constraints: List[str]) -> str:
        return f'''#!/usr/bin/env python3
"""
OMEGA Generated Code
Goal: {goal}
Constraints: {", ".join(constraints[:3])}
"""

import json
from datetime import datetime

def main():
    result = {{"status": "implemented", "timestamp": datetime.now().isoformat()}}
    print(json.dumps(result, indent=2))
    return result

if __name__ == "__main__":
    main()
'''
    
    def _generate_websocket_chat(self, goal: str, constraints: List[str]) -> str:
        return '''#!/usr/bin/env python3
"""
Real-Time WebSocket Chat Application
Generated by OMEGA-CODE Agentic-OS
Goal: Create a real-time chat application using WebSockets with rooms, private messaging, and message history
"""

import asyncio
import json
import secrets
from datetime import datetime
from typing import Dict, Set, List
from dataclasses import dataclass, field
from collections import defaultdict
import hashlib

# ============================================================================
# WEBSOCKET CHAT SERVER
# ============================================================================

class WebSocketChatServer:
    """Real-time chat with rooms, private messaging, history"""
    
    def __init__(self, host: str = "0.0.0.0", port: int = 8080):
        self.host = host
        self.port = port
        self.clients: Dict[str, Set] = defaultdict(set)
        self.user_sessions: Dict[str, str] = {}
        self.private_messages: Dict[tuple, List] = defaultdict(list)
        self.room_messages: Dict[str, List] = defaultdict(list)
        self.server = None
    
    async def handle_client(self, ws, path):
        """Handle WebSocket client connection"""
        session_id = secrets.token_urlsafe(16)
        username = None
        current_room = None
        
        try:
            await ws.send_json({
                "type": "welcome",
                "session_id": session_id,
                "message": "Connected to WebSocket Chat Server"
            })
            
            async for msg in ws:
                data = json.loads(msg)
                msg_type = data.get("type")
                
                if msg_type == "login":
                    username = data.get("username", f"user-{session_id[:6]}")
                    self.user_sessions[session_id] = username
                    await ws.send_json({"type": "login_ok", "username": username})
                
                elif msg_type == "join_room":
                    room = data.get("room", "general")
                    if current_room:
                        self.clients[current_room].discard(ws)
                    current_room = room
                    self.clients[room].add(ws)
                    await ws.send_json({
                        "type": "joined",
                        "room": room,
                        "history": self.room_messages[room][-50:]
                    })
                
                elif msg_type == "message":
                    if not current_room:
                        await ws.send_json({"type": "error", "message": "Join a room first"})
                        continue
                    
                    message = {
                        "id": secrets.token_urlsafe(8),
                        "user": username or "anonymous",
                        "text": data.get("text", ""),
                        "timestamp": datetime.now().isoformat()
                    }
                    self.room_messages[current_room].append(message)
                    
                    for client in self.clients[current_room]:
                        if client != ws:
                            await client.send_json({"type": "message", "data": message})
                
                elif msg_type == "private":
                    target = data.get("target")
                    text = data.get("text", "")
                    
                    message = {
                        "id": secrets.token_urlsafe(8),
                        "from": username or "anonymous",
                        "text": text,
                        "timestamp": datetime.now().isoformat()
                    }
                    
                    key = tuple(sorted([username or "anon", target]))
                    self.private_messages[key].append(message)
                    
                    await ws.send_json({
                        "type": "private_sent",
                        "target": target,
                        "message": message
                    })
                
                elif msg_type == "get_history":
                    room = data.get("room", current_room)
                    await ws.send_json({
                        "type": "history",
                        "room": room,
                        "messages": self.room_messages.get(room, [])[-50:]
                    })
                
                elif msg_type == "list_rooms":
                    await ws.send_json({
                        "type": "rooms",
                        "rooms": list(self.clients.keys())
                    })
        
        except Exception as e:
            print(f"Client error: {e}")
        finally:
            if current_room:
                self.clients[current_room].discard(ws)
            if session_id in self.user_sessions:
                del self.user_sessions[session_id]
    
    async def start(self):
        """Start WebSocket server"""
        self.server = await asyncio.start_server(
            self.handle_client, self.host, self.port
        )
        addr = self.server.sockets[0].getsockname()
        print(f"WebSocket Chat Server: ws://{addr[0]}:{addr[1]}")
        print("Features: Rooms, Private Messages, History")
        
        async with self.server:
            await self.server.serve_forever()


# ============================================================================
# MAIN
# ============================================================================

async def main():
    print("=" * 50)
    print("Real-Time WebSocket Chat Server")
    print("=" * 50)
    server = WebSocketChatServer()
    await server.start()

if __name__ == "__main__":
    asyncio.run(main())
'''
    
    def _generate_chat_server(self, goal: str, constraints: List[str]) -> str:
        return self._generate_websocket_chat(goal, constraints)
    
    def _generate_rest_api(self, goal: str, constraints: List[str]) -> str:
        return '''#!/usr/bin/env python3
"""
REST API Server
Generated by OMEGA-CODE Agentic-OS
Goal: {goal}
"""

from aiohttp import web
import json
from datetime import datetime

routes = web.RouteTableDef()

@routes.get('/')
async def index(request):
    return web.json_response({{"status": "ok", "service": "REST API", "time": datetime.now().isoformat()}})

@routes.get('/api/health')
async def health(request):
    return web.json_response({{"status": "healthy"}})

@routes.post('/api/data')
async def create_data(request):
    data = await request.json()
    return web.json_response({"id": "123", "data": data}, status=201)

@routes.get('/api/data/{id}')
async def get_data(request):
    id = request.match_info['id']
    return web.json_response({"id": id, "data": {"sample": "value"}})

@routes.put('/api/data/{id}')
async def update_data(request):
    id = request.match_info['id']
    data = await request.json()
    return web.json_response({"id": id, "updated": data})

@routes.delete('/api/data/{id}')
async def delete_data(request):
    id = request.match_info['id']
    return web.json_response({"deleted": id})

app = web.Application()
app.add_routes(routes)

if __name__ == "__main__":
    web.run_app(app, host='0.0.0.0', port=8080)
'''
    
    def _generate_rest_api_auth(self, goal: str, constraints: List[str]) -> str:
        return '''#!/usr/bin/env python3
"""
REST API with JWT Authentication, Rate Limiting, SQLite
Generated by OMEGA-CODE Agentic-OS
Goal: Create a REST API with authentication using JWT tokens, rate limiting, and SQLite database
"""

import asyncio
import hashlib
import secrets
import time
import json
from datetime import datetime, timedelta
from typing import Dict, Optional
from dataclasses import dataclass
from collections import defaultdict
from aiohttp import web
import sqlite3
from contextlib import contextmanager

# ============================================================================
# DATABASE
# ============================================================================

@contextmanager
def get_db(db_path="app.db"):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()

def init_database():
    with get_db() as conn:
        conn.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
        conn.execute("CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER, expires_at TIMESTAMP)")
        conn.execute("CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY, user_id INTEGER, name TEXT NOT NULL, data TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
        conn.commit()

# ============================================================================
# AUTHENTICATION
# ============================================================================

class AuthManager:
    def __init__(self):
        self.sessions: Dict[str, dict] = {{}}
        self.rate_limit: Dict[str, list] = defaultdict(list)
    
    def hash_password(self, password: str) -> str:
        return hashlib.sha256(password.encode()).hexdigest()
    
    def verify_password(self, password: str, password_hash: str) -> bool:
        return self.hash_password(password) == password_hash
    
    def create_token(self, user_id: int, username: str) -> str:
        token = secrets.token_urlsafe(32)
        self.sessions[token] = {{
            "user_id": user_id,
            "username": username,
            "expires": datetime.now() + timedelta(hours=24)
        }}
        return token
    
    def verify_token(self, token: str) -> Optional[dict]:
        session = self.sessions.get(token)
        if session and session["expires"] > datetime.now():
            return session
        return None
    
    def check_rate_limit(self, ip: str, limit: int = 100, window: int = 60) -> bool:
        now = time.time()
        self.rate_limit[ip] = [t for t in self.rate_limit[ip] if now - t < window]
        if len(self.rate_limit[ip]) >= limit:
            return False
        self.rate_limit[ip].append(now)
        return True

auth = AuthManager()

# ============================================================================
# MIDDLEWARE
# ============================================================================

@web.middleware
async def auth_middleware(request, handler):
    if request.path.startswith('/api/') and request.path not in ['/api/auth/login', '/api/auth/register']:
        token = request.headers.get('Authorization', '').replace('Bearer ', '')
        session = auth.verify_token(token)
        if not session:
            return web.json_response({{"error": "Unauthorized"}}, status=401)
        request['user'] = session
    return await handler(request)

@web.middleware
async def rate_limit_middleware(request, handler):
    ip = request.remote
    if not auth.check_rate_limit(ip):
        return web.json_response({{"error": "Rate limited"}}, status=429)
    return await handler(request)

# ============================================================================
# ROUTES
# ============================================================================

routes = web.RouteTableDef()

@routes.post('/api/auth/register')
async def register(request):
    data = await request.json()
    username = data.get('username')
    password = data.get('password')
    
    if not username or not password:
        return web.json_response({{"error": "Missing credentials"}}, status=400)
    
    password_hash = auth.hash_password(password)
    try:
        with get_db() as conn:
            conn.execute("INSERT INTO users (username, password_hash) VALUES (?, ?)",
                        (username, password_hash))
            conn.commit()
        return web.json_response({{"message": "Registered"}}, status=201)
    except sqlite3.IntegrityError:
        return web.json_response({{"error": "Username exists"}}, status=400)

@routes.post('/api/auth/login')
async def login(request):
    data = await request.json()
    username = data.get('username')
    password = data.get('password')
    
    with get_db() as conn:
        user = conn.execute("SELECT * FROM users WHERE username = ?", (username,)).fetchone()
    
    if not user or not auth.verify_password(password, user['password_hash']):
        return web.json_response({{"error": "Invalid credentials"}}, status=401)
    
    token = auth.create_token(user['id'], user['username'])
    return web.json_response({{"token": token, "username": user['username']}})

@routes.get('/api/items')
async def list_items(request):
    user = request.get('user')
    with get_db() as conn:
        items = conn.execute("SELECT * FROM items WHERE user_id = ?", (user['user_id'],)).fetchall()
    return web.json_response({{"items": [dict(i) for i in items]}})

@routes.post('/api/items')
async def create_item(request):
    user = request.get('user')
    data = await request.json()
    with get_db() as conn:
        conn.execute("INSERT INTO items (user_id, name, data) VALUES (?, ?, ?)",
                    (user['user_id'], data.get('name', ''), json.dumps(data)))
        conn.commit()
    return web.json_response({{"message": "Created"}}, status=201)

@routes.get('/api/items/{{id}}')
async def get_item(request):
    user = request.get('user')
    item_id = request.match_info['id']
    with get_db() as conn:
        item = conn.execute("SELECT * FROM items WHERE id = ? AND user_id = ?",
                           (item_id, user['user_id'])).fetchone()
    if not item:
        return web.json_response({{"error": "Not found"}}, status=404)
    return web.json_response(dict(item))

@routes.delete('/api/items/{{id}}')
async def delete_item(request):
    user = request.get('user')
    item_id = request.match_info['id']
    with get_db() as conn:
        conn.execute("DELETE FROM items WHERE id = ? AND user_id = ?", (item_id, user['user_id']))
        conn.commit()
    return web.json_response({{"message": "Deleted"}})

@routes.get('/health')
async def health(request):
    return web.json_response({{"status": "healthy"}})

# ============================================================================
# APP
# ============================================================================

app = web.Application(middlewares=[rate_limit_middleware, auth_middleware])
app.add_routes(routes)

if __name__ == "__main__":
    init_database()
    print("REST API Server: http://0.0.0.0:8080")
    print("Features: JWT Auth, Rate Limiting, SQLite, CRUD")
    web.run_app(app, host='0.0.0.0', port=8080)
'''


class CodeDiscriminator:
    """Discriminator: Evaluates code quality."""
    
    def __init__(self):
        self.quality_checks = [
            "error_handling",
            "type_safety", 
            "resource_cleanup",
            "input_validation",
            "documentation"
        ]
    
    def evaluate(self, code: str, goal: str) -> dict:
        """
        Evaluate code quality against goal.
        
        Returns:
            dict with 'score' (0-1), 'issues' list, 'passed' bool
        """
        issues = []
        score = 1.0
        
        if "try:" not in code and "except" not in code:
            issues.append("Missing error handling")
            score -= 0.2
        
        if "return" not in code:
            issues.append("Missing return statement")
            score -= 0.1
        
        if len(code) < 100:
            issues.append("Code seems too short")
            score -= 0.15
        
        if "# Goal:" not in code:
            issues.append("Missing goal documentation")
            score -= 0.1
        
        if "print" not in code and "return" not in code:
            issues.append("No output mechanism")
            score -= 0.15
        
        if "import" in code and code.count("import") > 5:
            issues.append("Too many imports - consider reducing")
            score -= 0.1
        
        if goal.lower()[:20] not in code.lower():
            issues.append("Goal not referenced in code")
            score -= 0.1
        
        return {
            "score": max(0.0, score),
            "issues": issues,
            "passed": score >= 0.7,
            "evaluated_at": datetime.now().isoformat()
        }


class OmegaGAN:
    """
    GAN-inspired self-correction system.
    
    - Generator creates code
    - Discriminator evaluates it
    - Loop continues until discriminator passes
    - Track temporal state for RNN-like behavior
    """
    
    def __init__(self, project_path: str):
        self.project_path = Path(project_path)
        self.generator = CodeGenerator()
        self.discriminator = CodeDiscriminator()
        
        self.history_file = self.project_path / "state" / "gan_history.json"
        self.history = self._load_history()
        
        self.state_file = self.project_path / "state" / "gan_state.json"
        self.state = self._load_state()
    
    def _load_history(self) -> List[dict]:
        """Load generation history."""
        if self.history_file.exists():
            try:
                return json.loads(self.history_file.read_text())
            except:
                pass
        return []
    
    def _load_state(self) -> dict:
        """Load temporal state (RNN-like)."""
        if self.state_file.exists():
            try:
                return json.loads(self.state_file.read_text())
            except:
                pass
        
        return {
            "total_generations": 0,
            "successful_generations": 0,
            "avg_score": 0.0,
            "common_issues": [],
            "recent_scores": []
        }
    
    def _save_history(self):
        """Save generation history."""
        self.history_file.parent.mkdir(parents=True, exist_ok=True)
        self.history_file.write_text(json.dumps(self.history[-100:], indent=2))
    
    def _save_state(self):
        """Save temporal state."""
        self.state_file.parent.mkdir(parents=True, exist_ok=True)
        self.state_file.write_text(json.dumps(self.state, indent=2))
    
    def generate_and_refine(
        self,
        goal: str,
        constraints: List[str],
        max_iterations: int = 5
    ) -> Tuple[str, dict]:
        """
        Generate code with iterative refinement.
        
        Loop:
        1. Generator creates code
        2. Discriminator evaluates
        3. If failed, Generator refines based on issues
        4. Repeat until passed or max_iterations
        """
        self.state["total_generations"] += 1
        
        current_code = ""
        iteration = 0
        best_code = ""
        best_score = 0.0
        
        while iteration < max_iterations:
            iteration += 1
            
            if iteration == 1:
                current_code = self.generator.generate(goal, constraints)
            else:
                issues = self.state.get("last_issues", [])
                refined_constraints = constraints + [f"Fix: {i}" for i in issues]
                current_code = self.generator.generate(goal, refined_constraints)
            
            evaluation = self.discriminator.evaluate(current_code, goal)
            
            self.history.append({
                "iteration": iteration,
                "goal": goal,
                "score": evaluation["score"],
                "issues": evaluation["issues"],
                "timestamp": datetime.now().isoformat()
            })
            
            self.state["last_issues"] = evaluation["issues"]
            self.state["recent_scores"].append(evaluation["score"])
            if len(self.state["recent_scores"]) > 10:
                self.state["recent_scores"] = self.state["recent_scores"][-10:]
            self.state["avg_score"] = sum(self.state["recent_scores"]) / len(self.state["recent_scores"])
            
            if evaluation["score"] > best_score:
                best_score = evaluation["score"]
                best_code = current_code
            
            if evaluation["passed"]:
                self.state["successful_generations"] += 1
                break
        
        self._save_history()
        self._save_state()
        
        return best_code, evaluation
    
    def get_temporal_context(self) -> dict:
        """Get RNN-like temporal state."""
        return {
            "total": self.state["total_generations"],
            "successful": self.state["successful_generations"],
            "success_rate": self.state["successful_generations"] / max(1, self.state["total_generations"]),
            "avg_score": self.state["avg_score"],
            "recent_trend": self._calculate_trend()
        }
    
    def _calculate_trend(self) -> str:
        """Calculate if scores are improving or declining."""
        scores = self.state["recent_scores"]
        if len(scores) < 3:
            return "insufficient_data"
        
        recent = sum(scores[-3:]) / 3
        earlier = sum(scores[:3]) / 3
        
        if recent > earlier + 0.1:
            return "improving"
        elif recent < earlier - 0.1:
            return "declining"
        return "stable"


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: omega_gan.py <project_path>")
        sys.exit(1)
    
    project_path = sys.argv[1]
    gan = OmegaGAN(project_path)
    
    goal = "Create a function that validates email addresses"
    constraints = ["Use regex", "Handle edge cases", "Return boolean"]
    
    print(f"Running GAN for: {goal}\n")
    
    code, evaluation = gan.generate_and_refine(goal, constraints)
    
    print(f"Final Score: {evaluation['score']:.2f}")
    print(f"Passed: {evaluation['passed']}")
    print(f"Iterations: {len([h for h in gan.history if h['goal'] == goal])}")
    print("\n--- Generated Code ---")
    print(code[:500] + "..." if len(code) > 500 else code)
    
    print("\n--- Temporal Context ---")
    context = gan.get_temporal_context()
    for k, v in context.items():
        print(f"  {k}: {v}")
