#!/bin/bash
# OMEGA-CODE Git Automation
# Atomic commits with iteration metadata

set -e

PROJECT_DIR="${1:-.}"
BRANCH_PREFIX="omega"
COMMIT_MSG_FILE="/tmp/omega_commit_$$.msg"

# Initialize if needed
if [ ! -d "$PROJECT_DIR/.git" ]; then
    echo "Initializing git in $PROJECT_DIR"
    cd "$PROJECT_DIR"
    git init
    git config user.name "OMEGA-CODE Agent"
    git config user.email "omega@paradise.local"
fi

# Get current iteration
ITERATION="${2:-1}"
STATUS="${3:-PASS}"
REASON="${4:-auto-commit}"

cd "$PROJECT_DIR"

# Create branch for this feature/iteration
BRANCH_NAME="${BRANCH_PREFIX}-iter-${ITERATION}"

# Check if branch exists, create if not
if ! git rev-parse --verify "$BRANCH_NAME" >/dev/null 2>&1; then
    git checkout -b "$BRANCH_NAME"
else
    git checkout "$BRANCH_NAME"
fi

# Stage all changes
git add -A

# Create atomic commit message
cat > "$COMMIT_MSG_FILE" << EOF
[ITERATION-${ITERATION}] [STATUS: ${STATUS}] [REASON: ${REASON}]

Generated by OMEGA-CODE autonomous agent
Timestamp: $(date -Iseconds)
EOF

# Commit
if git diff --staged --quiet; then
    echo "No changes to commit"
else
    git commit -F "$COMMIT_MSG_FILE"
    echo "Committed to branch: $BRANCH_NAME"
fi

# Cleanup
rm -f "$COMMIT_MSG_FILE"

# Show status
git log --oneline -5
