#!/bin/bash
# =============================================================================
# OMEGA-CODE Seamless Execution Engine
# =============================================================================
# Purpose: Persistence, Atomic Versioning, and Fault Tolerance
# Features:
#   - Exponential backoff for LLM delays
#   - Heartbeat monitoring
#   - Atomic Git commits per iteration
#   - Branch strategy (prod/wip)
#   - Never-quit with hibernation
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_NAME="${PROJECT_NAME:-default}"
PROJECT_DIR="${SCRIPT_DIR}/projects/${PROJECT_NAME}"
LOG_DIR="${PROJECT_DIR}/logs"
SRC_DIR="${PROJECT_DIR}/src"
STATE_DIR="${PROJECT_DIR}/state"

# Configuration
RETRY_DELAY=5
MAX_RETRIES=10
MAX_ITERATIONS="${MAX_ITERATIONS:-50}"
VACUUM_INTERVAL=100
ITERATION_COUNT=0

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

timestamp() {
    date +"%Y-%m-%d %H:%M:%S"
}

git_timestamp() {
    date +"%Y-%m-%d_%H-%M-%S"
}

# =============================================================================
# INITIALIZATION
# =============================================================================

init_project() {
    log_info "Initializing OMEGA-CODE project: ${PROJECT_NAME}"
    
    # Create directories
    mkdir -p "${SRC_DIR}"
    mkdir -p "${LOG_DIR}"
    mkdir -p "${STATE_DIR}"
    mkdir -p "${PROJECT_DIR}/self-eval-logs"
    mkdir -p "${PROJECT_DIR}/memory"
    mkdir -p "${PROJECT_DIR}/outputs"
    
    # Initialize Git if not exists
    if [ ! -d "${SRC_DIR}/.git" ]; then
        log_info "Initializing Git repository..."
        git init "${SRC_DIR}"
        git config user.name "OMEGA-CODE Agent"
        git config user.email "omega@paradise.local"
        
        # Create initial commit
        echo "# ${PROJECT_NAME}" > "${SRC_DIR}/README.md"
        echo "Generated by OMEGA-CODE at $(timestamp)" >> "${SRC_DIR}/README.md"
        git -C "${SRC_DIR}" add .
        git -C "${SRC_DIR}" commit -m "OMEGA: Initializing persistent state"
        log_success "Git repository initialized"
    fi
    
    # Initialize state snapshot if not exists
    if [ ! -f "${STATE_DIR}/omega_state.db" ]; then
        log_info "Creating initial state..."
        python3 -c "
import sqlite3
import os
os.makedirs('${STATE_DIR}', exist_ok=True)
conn = sqlite3.connect('${STATE_DIR}/omega_state.db')
conn.execute('CREATE TABLE IF NOT EXISTS forge_state (id INTEGER PRIMARY KEY, goal TEXT, code TEXT, status TEXT, logs TEXT)')
conn.execute('CREATE TABLE IF NOT EXISTS failures (id INTEGER PRIMARY KEY, goal TEXT, error TEXT, error_type TEXT, timestamp TEXT)')
conn.commit()
conn.close()
"
        log_success "State database created"
    fi
    
    log_success "Project initialized"
}

# =============================================================================
# LLM CALL WITH PATIENCE & EXPONENTIAL BACKOFF
# =============================================================================

call_llm_with_patience() {
    local attempt=1
    local success=false
    local output=""
    
    log_info "Calling LLM with patience (attempt ${attempt}/${MAX_RETRIES})"
    
    while [ "$success" = false ] && [ $attempt -le $MAX_RETRIES ]; do
        # Call the core python logic
        output=$(python3 "${SCRIPT_DIR}/engine/omega_forge.py" 2>&1)
        exit_code=$?
        
        # Check for LLM delays or rate limits
        if echo "$output" | grep -q "LLM_DELAY\|RATE_LIMIT\|429\|503\|timeout"; then
            local wait_time=$((RETRY_DELAY * attempt))
            log_warning "LLM Overloaded or Rate Limited. Throttling for ${wait_time}s..."
            sleep $wait_time
            ((attempt++))
        elif [ $exit_code -eq 0 ]; then
            success=true
            echo "$output"
        elif echo "$output" | grep -q "CRITICAL\|FATAL"; then
            log_error "Critical failure detected"
            echo "$output"
            return 1
        else
            # LLM responded but with non-zero exit - might be partial success
            if echo "$output" | grep -q "BASE CASE REACHED\|SUCCESS"; then
                success=true
                echo "$output"
            else
                log_warning "Non-zero exit, retrying..."
                sleep $RETRY_DELAY
                ((attempt++))
            fi
        fi
    done
    
    if [ "$success" = false ]; then
        log_error "LLM Lost after ${MAX_RETRIES} attempts. Serializing state and hibernating."
        hibernate_llm_failure
        return 1
    fi
    
    return 0
}

# =============================================================================
# HIBERNATION MODE (When LLM is unavailable)
# =============================================================================

hibernate_llm_failure() {
    log_warning "Entering hibernation mode..."
    
    # Serialize current state
    cat > "${STATE_DIR}/hibernate.json" << EOF
{
    "project": "${PROJECT_NAME}",
    "hibernated_at": "$(timestamp)",
    "iteration_count": ${ITERATION_COUNT},
    "reason": "LLM_UNAVAILABLE"
}
EOF
    
    # Commit current state
    commit_iteration "HIBERNATE" "LLM unavailable, entering hibernation"
    
    log_info "Hibernation complete. State serialized."
    log_info "System will wake when LLM becomes available."
    log_info "Check logs: tail -f ${LOG_DIR}/omega_engine.log"
    
    # Wait and retry
    while true; do
        log_info "Checking LLM availability..."
        sleep 60
        
        # Test LLM
        if python3 -c "print('test')" > /dev/null 2>&1; then
            log_success "LLM available, resuming operations"
            rm -f "${STATE_DIR}/hibernate.json"
            return 0
        fi
    done
}

# =============================================================================
# GIT VERSION CONTROL
# =============================================================================

commit_iteration() {
    local status="$1"
    local message="$2"
    local ts=$(git_timestamp)
    
    # Add all changes
    git -C "${SRC_DIR}" add .
    
    # Check if there are changes
    if git -C "${SRC_DIR}" diff --staged --quiet; then
        log_info "No changes to commit"
        return 0
    fi
    
    # Create atomic commit message
    local commit_msg="[ITERATION-${ITERATION_COUNT}] [STATUS: ${status}] [TIME: ${ts}]
    
Project: ${PROJECT_NAME}
Message: ${message}
Generated by OMEGA-CODE Engine"
    
    git -C "${SRC_DIR}" commit -m "${commit_msg}"
    log_success "Committed: ${status}"
}

create_production_branch() {
    local ts=$(git_timestamp)
    local branch_name="prod-${ts}"
    
    git -C "${SRC_DIR}" checkout -b "${branch_name}"
    log_success "Production branch created: ${branch_name}"
}

# =============================================================================
# HEALTH MONITORING
# =============================================================================

heartbeat() {
    log_info "Heartbeat: $(timestamp) | Iteration: ${ITERATION_COUNT}"
}

check_health() {
    # Check Docker
    if docker info > /dev/null 2>&1; then
        echo "docker: ok"
    else
        echo "docker: unavailable"
    fi
    
    # Check disk space
    local disk_usage=$(df -h "${PROJECT_DIR}" | tail -1 | awk '{print $5}' | sed 's/%//')
    if [ "$disk_usage" -gt 90 ]; then
        log_warning "Disk usage high: ${disk_usage}%"
    fi
}

# =============================================================================
# VACUUM PROTOCOL (Periodic Cleanup)
# =============================================================================

run_vacuum() {
    if [ $((ITERATION_COUNT % VACUUM_INTERVAL)) -eq 0 ] && [ $ITERATION_COUNT -gt 0 ]; then
        log_info "Running vacuum protocol..."
        python3 "${SCRIPT_DIR}/engine/omega_vacuum.py" || log_warning "Vacuum failed"
    fi
}

# =============================================================================
# MAIN NEVER-QUIT LOOP
# =============================================================================

run_never_quit_loop() {
    log_info "Starting OMEGA-CODE Never-Quit Loop"
    log_info "Project: ${PROJECT_NAME}"
    log_info "Max Iterations: ${MAX_ITERATIONS}"
    
    init_project
    
    while true; do
        ((ITERATION_COUNT++))
        
        echo ""
        log_info "=========================================="
        log_info "ITERATION ${ITERATION_COUNT}/${MAX_ITERATIONS}"
        log_info "=========================================="
        
        # Phase: RECOLLECT
        log_info "Phase: RECOLLECT"
        heartbeat
        check_health
        
        # Phase: INTELLIGENCE (Patient & Persistent)
        log_info "Phase: RECTIFY"
        if ! call_llm_with_patience; then
            log_error "LLM call failed after retries"
            continue
        fi
        
        # Phase: VERIFY (Using DinD Sandbox)
        log_info "Phase: VERIFY"
        
        # Run environment verification
        if python3 "${SCRIPT_DIR}/docker/verify_env.py" > /dev/null 2>&1; then
            commit_iteration "PASS" "Logic verified in sandbox"
            log_success "Iteration PASSED"
            
            # Create production branch on success
            if [ "$ITERATION_COUNT" -gt 1 ]; then
                create_production_branch || true
            fi
        else
            commit_iteration "FAIL" "Sandbox failure detected, recursing"
            log_warning "Iteration FAILED, recursing..."
        fi
        
        # Phase: VACUUM (Periodic cleanup)
        run_vacuum
        
        # Check iteration limit
        if [ $ITERATION_COUNT -ge $MAX_ITERATIONS ]; then
            log_warning "Max iterations reached"
            commit_iteration "MAX_ITERATIONS" "Reached maximum iteration count"
            break
        fi
        
        # Sleep between iterations
        sleep 2
    done
    
    log_success "Never-Quit Loop completed"
    log_info "Total iterations: ${ITERATION_COUNT}"
}

# =============================================================================
# COMMAND HANDLERS
# =============================================================================

cmd_start() {
    run_never_quit_loop
}

cmd_resume() {
    log_info "Resuming from hibernation..."
    
    if [ -f "${STATE_DIR}/hibernate.json" ]; then
        local hibernated_at=$(grep hibernated_at "${STATE_DIR}/hibernate.json" | cut -d'"' -f4)
        log_info "Last hibernated at: ${hibernated_at}"
        ITERATION_COUNT=$(grep iteration_count "${STATE_DIR}/hibernate.json" | cut -d':' -f2 | tr -d ' ,')
        log_info "Resuming from iteration: ${ITERATION_COUNT}"
    fi
    
    run_never_quit_loop
}

cmd_status() {
    echo "OMEGA-CODE Status"
    echo "================="
    echo "Project: ${PROJECT_NAME}"
    echo "Iterations: ${ITERATION_COUNT}"
    echo "State: ${STATE_DIR}"
    
    if [ -f "${STATE_DIR}/hibernate.json" ]; then
        echo "Status: HIBERNATING"
    else
        echo "Status: RUNNING"
    fi
    
    check_health
}

cmd_test() {
    log_info "Running test iteration..."
    ITERATION_COUNT=1
    run_never_quit_loop
}

# =============================================================================
# SCRIPT ENTRY POINT
# =============================================================================

CMD="${1:-start}"

case "$CMD" in
    start)
        cmd_start
        ;;
    resume)
        cmd_resume
        ;;
    status)
        cmd_status
        ;;
    test)
        cmd_test
        ;;
    *)
        echo "Usage: $0 {start|resume|status|test}"
        exit 1
        ;;
esac
