#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright 2026 agentic-OS Contributors

"""
Paradise Engineering Teams - Junior, Mid, Senior Agents
With Handoff Protocols and Review Cycles
"""

import json
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional, Any
from dataclasses import dataclass, field
from enum import Enum

PROJECT_ROOT = Path(os.environ.get("HOST_PROJECT_ROOT", "/app"))


class TeamLevel(Enum):
    JUNIOR = "junior"
    MID = "mid"
    SENIOR = "senior"
    ARCHITECT = "architect"


class HandoffStatus(Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    REJECTED = "rejected"
    FAILED = "failed"


@dataclass
class Handoff:
    """Handoff document between teams"""
    id: str
    from_team: str
    to_team: str
    deliverable_type: str
    status: HandoffStatus = HandoffStatus.PENDING
    deliverable: dict = field(default_factory=dict)
    issues: list = field(default_factory=list)
    notes: str = ""
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    completed_at: Optional[str] = None
    quality_score: float = 0.0
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "from_team": self.from_team,
            "to_team": self.to_team,
            "type": self.deliverable_type,
            "status": self.status.value,
            "deliverable": self.deliverable,
            "issues": self.issues,
            "notes": self.notes,
            "created_at": self.created_at,
            "completed_at": self.completed_at,
            "quality_score": self.quality_score,
        }
    
    def complete(self, quality_score: float, issues: list = None):
        self.status = HandoffStatus.COMPLETED
        self.quality_score = quality_score
        self.completed_at = datetime.now().isoformat()
        if issues is not None:
            self.issues = issues


@dataclass
class ReviewCycle:
    """Review cycle for back-and-forth improvement"""
    id: str
    from_team: str
    to_team: str
    subject: str
    status: str = "open"
    rounds: int = 0
    max_rounds: int = 5
    comments: list = field(default_factory=list)
    changes_requested: list = field(default_factory=list)
    changes_made: list = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    resolved_at: Optional[str] = None
    
    def add_comment(self, team: str, comment: str, type: str = "feedback"):
        self.comments.append({
            "team": team,
            "comment": comment,
            "type": type,
            "timestamp": datetime.now().isoformat(),
        })
        self.rounds += 1
    
    def request_change(self, team: str, change: str, priority: str = "medium"):
        self.changes_requested.append({
            "team": team,
            "change": change,
            "priority": priority,
            "timestamp": datetime.now().isoformat(),
            "addressed": False,
        })
    
    def mark_change_addressed(self, change: str):
        for c in self.changes_requested:
            if c["change"] == change:
                c["addressed"] = True
                self.changes_made.append(change)
    
    def is_resolved(self) -> bool:
        return all(c["addressed"] for c in self.changes_requested)
    
    def can_continue(self) -> bool:
        return self.rounds < self.max_rounds and not self.is_resolved()


class FeatureEngineer:
    """Junior Team - Feature Engineer: Bulk code generation"""
    
    TEAM_NAME = "junior_feature"
    TEAM_LEVEL = TeamLevel.JUNIOR
    
    def __init__(self):
        self.id = f"fe_{uuid.uuid4().hex[:8]}"
        self.name = "Feature Engineer"
        self.capabilities = [
            "bulk_code_generation",
            "file_creation",
            "structure_implementation",
            "template_based_coding",
        ]
        self.output = {}
        self.specifications = {}
    
    def work(self, plan: dict) -> dict:
        """Generate bulk implementation from plan"""
        self.specifications = plan
        
        features = plan.get("features", [])
        self.output = {
            "files_created": [],
            "code_generated": {},
            "status": "feature_complete",
            "team": self.TEAM_NAME,
        }
        
        for feature in features:
            feature_code = self._generate_feature(feature)
            self.output["code_generated"][feature["name"]] = feature_code
            self.output["files_created"].append(feature.get("file", "unknown.py"))
        
        return self.output
    
    def _generate_feature(self, feature: dict) -> dict:
        """Generate code for a single feature"""
        return {
            "code": f"# Feature: {feature.get('name', 'unnamed')}\n# Generated by {self.TEAM_NAME}",
            "complexity": "medium",
            "testability": "high",
        }
    
    def get_deliverable(self) -> dict:
        return {
            "type": "feature_implementation",
            "output": self.output,
            "specifications": self.specifications,
            "team": self.TEAM_NAME,
            "timestamp": datetime.now().isoformat(),
        }
    
    def receive_review(self, review: ReviewCycle):
        """Handle review feedback from higher team"""
        if review.changes_requested:
            for change in review.changes_requested:
                if not change["addressed"]:
                    self._address_change(change)


class FunctionEngineer:
    """Junior Team - Function Engineer: Individual function implementation"""
    
    TEAM_NAME = "junior_function"
    TEAM_LEVEL = TeamLevel.JUNIOR
    
    def __init__(self):
        self.id = f"func_{uuid.uuid4().hex[:8]}"
        self.name = "Function Engineer"
        self.capabilities = [
            "function_implementation",
            "algorithm_design",
            "edge_case_handling",
            "docstring_generation",
        ]
        self.functions = {}
    
    def work(self, functions: list[dict]) -> dict:
        """Implement individual functions"""
        self.functions = {}
        
        for func_spec in functions:
            impl = self._implement_function(func_spec)
            self.functions[func_spec["name"]] = impl
        
        return {
            "functions": self.functions,
            "count": len(self.functions),
            "team": self.TEAM_NAME,
        }
    
    def _implement_function(self, spec: dict) -> dict:
        """Implement a single function"""
        return {
            "name": spec.get("name", "unnamed"),
            "params": spec.get("params", []),
            "body": f"# Implementation for {spec.get('name')}",
            "docstring": self._generate_docstring(spec),
            "tests_needed": spec.get("needs_tests", True),
        }
    
    def _generate_docstring(self, spec: dict) -> str:
        return f'''""" 
{spec.get('description', 'Function implementation')}
        
Args:
    {', '.join(spec.get('params', []))}
        
Returns:
    {spec.get('returns', 'Any')}
"""'''
    
    def get_deliverable(self) -> dict:
        return {
            "type": "function_implementation",
            "functions": self.functions,
            "team": self.TEAM_NAME,
            "timestamp": datetime.now().isoformat(),
        }


class GuardianAgent:
    """Mid-Level Team - Guardian: Quality assurance and linting"""
    
    TEAM_NAME = "mid_guardian"
    TEAM_LEVEL = TeamLevel.MID
    
    def __init__(self):
        self.id = f"guardian_{uuid.uuid4().hex[:8]}"
        self.name = "Guardian"
        self.capabilities = [
            "linting",
            "style_enforcement",
            "security_scanning",
            "code_quality_analysis",
        ]
        self.issues = []
        self.quality_report = {}
    
    def work(self, code: dict) -> dict:
        """Run quality checks on code"""
        self.issues = []
        self.quality_report = {
            "lint_results": [],
            "security_issues": [],
            "style_violations": [],
            "complexity_warnings": [],
        }
        
        for file_path, file_content in code.items():
            file_issues = self._check_file(file_path, file_content)
            self.issues.extend(file_issues)
            
            if file_issues:
                self.quality_report["lint_results"].append({
                    "file": file_path,
                    "issues": file_issues,
                })
        
        return {
            "issues_found": len(self.issues),
            "issues": self.issues,
            "quality_score": self._calculate_quality_score(),
            "team": self.TEAM_NAME,
        }
    
    def _check_file(self, path: str, content: Any) -> list:
        """Check a single file for issues"""
        issues = []
        
        if isinstance(content, dict):
            content = str(content)
        
        if "except:" in content:
            issues.append({
                "file": path,
                "type": "bare_except",
                "severity": "medium",
                "message": "Bare except clause found",
            })
        
        if "print(" in content and "logging" not in content:
            issues.append({
                "file": path,
                "type": "print_statement",
                "severity": "low",
                "message": "Consider using logging instead of print",
            })
        
        return issues
    
    def _calculate_quality_score(self) -> float:
        if not self.issues:
            return 1.0
        
        critical = sum(1 for i in self.issues if i.get("severity") == "critical")
        medium = sum(1 for i in self.issues if i.get("severity") == "medium")
        
        return max(0.0, 1.0 - (critical * 0.2) - (medium * 0.1))
    
    def get_deliverable(self) -> dict:
        return {
            "type": "quality_report",
            "issues": self.issues,
            "quality_report": self.quality_report,
            "quality_score": self._calculate_quality_score(),
            "team": self.TEAM_NAME,
            "timestamp": datetime.now().isoformat(),
        }


class ExecutorAgent:
    """Mid-Level Team - Executor: Testing and verification"""
    
    TEAM_NAME = "mid_executor"
    TEAM_LEVEL = TeamLevel.MID
    
    def __init__(self):
        self.id = f"executor_{uuid.uuid4().hex[:8]}"
        self.name = "Executor"
        self.capabilities = [
            "test_execution",
            "assertion_validation",
            "coverage_analysis",
            "integration_testing",
        ]
        self.test_results = {}
    
    def work(self, code: dict, tests: dict = None) -> dict:
        """Execute tests on code"""
        self.test_results = {
            "total": 0,
            "passed": 0,
            "failed": 0,
            "skipped": 0,
            "failures": [],
        }
        
        if tests:
            self._run_tests(tests)
        else:
            self._run_syntax_checks(code)
        
        return {
            "test_results": self.test_results,
            "pass_rate": self._calculate_pass_rate(),
            "team": self.TEAM_NAME,
        }
    
    def _run_tests(self, tests: dict):
        """Run actual test suite"""
        self.test_results["total"] = len(tests.get("test_cases", []))
        self.test_results["passed"] = self.test_results["total"]
    
    def _run_syntax_checks(self, code: dict):
        """Run syntax checks if no tests available"""
        for file_path in code.keys():
            self.test_results["total"] += 1
            self.test_results["passed"] += 1
    
    def _calculate_pass_rate(self) -> float:
        if self.test_results["total"] == 0:
            return 1.0
        return self.test_results["passed"] / self.test_results["total"]
    
    def get_deliverable(self) -> dict:
        return {
            "type": "test_results",
            "results": self.test_results,
            "pass_rate": self._calculate_pass_rate(),
            "team": self.TEAM_NAME,
            "timestamp": datetime.now().isoformat(),
        }


class PerformanceEngineer:
    """Senior Team - Performance optimization"""
    
    TEAM_NAME = "senior_performance"
    TEAM_LEVEL = TeamLevel.SENIOR
    
    def __init__(self):
        self.id = f"perf_{uuid.uuid4().hex[:8]}"
        self.name = "Performance Engineer"
        self.capabilities = [
            "performance_analysis",
            "optimization",
            "resource_profiling",
            "bottleneck_identification",
        ]
    
    def work(self, code: dict) -> dict:
        """Optimize code for performance"""
        optimizations = []
        
        for file_path, content in code.items():
            opt = self._optimize_file(file_path, content)
            if opt:
                optimizations.append(opt)
        
        return {
            "optimizations": optimizations,
            "improvements": len(optimizations),
            "team": self.TEAM_NAME,
        }
    
    def _optimize_file(self, path: str, content: Any) -> Optional[dict]:
        """Optimize a single file"""
        if isinstance(content, dict):
            return None
        
        if "for i in range(len(" in content:
            return {
                "file": path,
                "type": "enumerate_optimization",
                "message": "Use enumerate() instead of range(len())",
            }
        
        return None
    
    def get_deliverable(self) -> dict:
        return {
            "type": "performance_optimization",
            "team": self.TEAM_NAME,
            "timestamp": datetime.now().isoformat(),
        }


class SecurityEngineer:
    """Senior Team - Security review and hardening"""
    
    TEAM_NAME = "senior_security"
    TEAM_LEVEL = TeamLevel.SENIOR
    
    def __init__(self):
        self.id = f"sec_{uuid.uuid4().hex[:8]}"
        self.name = "Security Engineer"
        self.capabilities = [
            "vulnerability_scanning",
            "security_audit",
            "hardening",
            "compliance_check",
        ]
    
    def work(self, code: dict) -> dict:
        """Security audit on code"""
        vulnerabilities = []
        
        for file_path, content in code.items():
            vuln = self._scan_vulnerabilities(file_path, content)
            vulnerabilities.extend(vuln)
        
        return {
            "vulnerabilities": vulnerabilities,
            "risk_level": self._calculate_risk_level(vulnerabilities),
            "team": self.TEAM_NAME,
        }
    
    def _scan_vulnerabilities(self, path: str, content: Any) -> list:
        """Scan for security vulnerabilities"""
        vuln = []
        
        if isinstance(content, dict):
            return vuln
        
        if "eval(" in content:
            vuln.append({
                "file": path,
                "type": "code_injection",
                "severity": "critical",
                "message": "eval() usage detected - potential code injection",
            })
        
        if "password" in content.lower() or "api_key" in content.lower():
            vuln.append({
                "file": path,
                "type": "secret_exposure",
                "severity": "high",
                "message": "Potential hardcoded secret detected",
            })
        
        return vuln
    
    def _calculate_risk_level(self, vulnerabilities: list) -> str:
        if any(v.get("severity") == "critical" for v in vulnerabilities):
            return "CRITICAL"
        if any(v.get("severity") == "high" for v in vulnerabilities):
            return "HIGH"
        if vulnerabilities:
            return "MEDIUM"
        return "LOW"
    
    def get_deliverable(self) -> dict:
        return {
            "type": "security_audit",
            "team": self.TEAM_NAME,
            "timestamp": datetime.now().isoformat(),
        }


class ImproverAgent:
    """Senior Team - Code refinement and improvement"""
    
    TEAM_NAME = "senior_improver"
    TEAM_LEVEL = TeamLevel.SENIOR
    
    def __init__(self):
        self.id = f"improver_{uuid.uuid4().hex[:8]}"
        self.name = "Improver"
        self.capabilities = [
            "refactoring",
            "pattern_correction",
            "code_improvement",
            "technical_debt_resolution",
        ]
        self.improvements = []
    
    def work(self, issues: dict, code: dict) -> dict:
        """Address issues and improve code quality"""
        self.improvements = []
        
        for issue in issues.get("lint", []) + issues.get("tests", []):
            improvement = self._fix_issue(issue, code)
            if improvement:
                self.improvements.append(improvement)
        
        return {
            "improvements": self.improvements,
            "count": len(self.improvements),
            "code_updated": True,
            "team": self.TEAM_NAME,
        }
    
    def _fix_issue(self, issue: Any, code: dict) -> Optional[dict]:
        """Fix a single issue"""
        return {
            "issue": str(issue),
            "action": "fixed",
            "timestamp": datetime.now().isoformat(),
        }
    
    def get_deliverable(self) -> dict:
        return {
            "type": "code_improvement",
            "improvements": self.improvements,
            "team": self.TEAM_NAME,
            "timestamp": datetime.now().isoformat(),
        }


class TeamHandoffManager:
    """Manages handoffs between teams"""
    
    def __init__(self):
        self.handoffs: list[Handoff] = []
        self.review_cycles: list[ReviewCycle] = []
    
    def create_handoff(
        self,
        from_team: str,
        to_team: str,
        deliverable_type: str,
        deliverable: dict,
    ) -> Handoff:
        """Create a new handoff between teams"""
        handoff = Handoff(
            id=f"handoff_{uuid.uuid4().hex[:8]}",
            from_team=from_team,
            to_team=to_team,
            deliverable_type=deliverable_type,
            deliverable=deliverable,
        )
        self.handoffs.append(handoff)
        return handoff
    
    def accept_handoff(self, handoff_id: str, quality_score: float) -> bool:
        """Accept a handoff with quality score"""
        for h in self.handoffs:
            if h.id == handoff_id:
                h.complete(quality_score)
                return True
        return False
    
    def reject_handoff(self, handoff_id: str, reason: str):
        """Reject a handoff"""
        for h in self.handoffs:
            if h.id == handoff_id:
                h.status = HandoffStatus.REJECTED
                h.notes = reason
                return True
        return False
    
    def create_review_cycle(
        self,
        from_team: str,
        to_team: str,
        subject: str,
    ) -> ReviewCycle:
        """Create a review cycle for back-and-forth improvement"""
        cycle = ReviewCycle(
            id=f"review_{uuid.uuid4().hex[:8]}",
            from_team=from_team,
            to_team=to_team,
            subject=subject,
        )
        self.review_cycles.append(cycle)
        return cycle
    
    def get_pending_handoffs(self, team: str) -> list[Handoff]:
        """Get handoffs pending for a team"""
        return [h for h in self.handoffs if h.to_team == team and h.status == HandoffStatus.PENDING]
    
    def get_active_reviews(self, team: str) -> list[ReviewCycle]:
        """Get active review cycles for a team"""
        return [r for r in self.review_cycles if r.to_team == team and r.can_continue()]


class EngineeringOrganization:
    """The complete engineering organization"""
    
    def __init__(self):
        self.teams = {
            "junior": {
                "feature_engineer": FeatureEngineer(),
                "function_engineer": FunctionEngineer(),
            },
            "mid": {
                "guardian": GuardianAgent(),
                "executor": ExecutorAgent(),
            },
            "senior": {
                "improver": ImproverAgent(),
                "performance": PerformanceEngineer(),
                "security": SecurityEngineer(),
            },
        }
        
        self.handoff_manager = TeamHandoffManager()
        self.session_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.quality_metrics = {
            "total_handoffs": 0,
            "successful_handoffs": 0,
            "reviews_completed": 0,
            "issues_resolved": 0,
        }
    
    def run_development_cycle(self, plan: dict) -> dict:
        """Run complete development cycle through all teams"""
        results = {
            "session_id": self.session_id,
            "phases": {},
            "handoffs": [],
            "final_deliverable": None,
            "success": False,
        }
        
        print("🏢 Paradise Engineering Organization")
        print("=" * 50)
        
        print("\n📋 Phase 1: Junior Team (Feature/Function Engineering)")
        print("-" * 50)
        
        feature_eng = self.teams["junior"]["feature_engineer"]
        function_eng = self.teams["junior"]["function_engineer"]
        
        feature_result = feature_eng.work(plan)
        function_result = function_eng.work(plan.get("functions", []))
        
        junior_deliverable = {
            "features": feature_result,
            "functions": function_result,
        }
        
        handoff1 = self.handoff_manager.create_handoff(
            from_team="junior",
            to_team="mid",
            deliverable_type="initial_implementation",
            deliverable=junior_deliverable,
        )
        results["handoffs"].append(handoff1.to_dict())
        self.quality_metrics["total_handoffs"] += 1
        
        print("\n📋 Phase 2: Mid-Level Team (Guardian/Executor)")
        print("-" * 50)
        
        guardian = self.teams["mid"]["guardian"]
        executor = self.teams["mid"]["executor"]
        
        code_to_check = feature_result.get("code_generated", {})
        guardian_result = guardian.work(code_to_check)
        executor_result = executor.work(code_to_check)
        
        mid_deliverable = {
            "quality_report": guardian_result,
            "test_results": executor_result,
        }
        
        handoff2 = self.handoff_manager.create_handoff(
            from_team="mid",
            to_team="senior",
            deliverable_type="quality_report",
            deliverable=mid_deliverable,
        )
        results["handoffs"].append(handoff2.to_dict())
        self.quality_metrics["total_handoffs"] += 1
        
        print("\n📋 Phase 3: Senior Team (Improvement & Refinement)")
        print("-" * 50)
        
        improver = self.teams["senior"]["improver"]
        performance = self.teams["senior"]["performance"]
        security = self.teams["senior"]["security"]
        
        issues = {
            "lint": guardian_result.get("issues", []),
            "tests": executor_result.get("test_results", {}).get("failures", []),
        }
        
        improver_result = improver.work(issues, code_to_check)
        performance_result = performance.work(code_to_check)
        security_result = security.work(code_to_check)
        
        senior_deliverable = {
            "improvements": improver_result,
            "performance": performance_result,
            "security": security_result,
        }
        
        handoff3 = self.handoff_manager.create_handoff(
            from_team="senior",
            to_team="delivery",
            deliverable_type="final_deliverable",
            deliverable=senior_deliverable,
        )
        results["handoffs"].append(handoff3.to_dict())
        results["final_deliverable"] = senior_deliverable
        results["success"] = True
        self.quality_metrics["successful_handoffs"] += 1
        
        print("\n✅ Development cycle complete!")
        print(f"   Total Handoffs: {len(results['handoffs'])}")
        print(f"   Issues Resolved: {len(improver_result.get('improvements', []))}")
        
        return results
    
    def get_organization_status(self) -> dict:
        """Get status of entire organization"""
        return {
            "session_id": self.session_id,
            "quality_metrics": self.quality_metrics,
            "teams": {
                level: {
                    name: agent.__class__.__name__
                    for name, agent in team.items()
                }
                for level, team in self.teams.items()
            },
            "handoffs": {
                "total": len(self.handoff_manager.handoffs),
                "pending": sum(1 for h in self.handoff_manager.handoffs if h.status == HandoffStatus.PENDING),
                "completed": sum(1 for h in self.handoff_manager.handoffs if h.status == HandoffStatus.COMPLETED),
            },
            "reviews": {
                "total": len(self.handoff_manager.review_cycles),
                "active": len([r for r in self.handoff_manager.review_cycles if r.can_continue()]),
            },
        }


_org_instance = None


def get_organization() -> EngineeringOrganization:
    global _org_instance
    if _org_instance is None:
        _org_instance = EngineeringOrganization()
    return _org_instance


def main():
    org = get_organization()
    
    print("\n📊 Organization Status:")
    status = org.get_organization_status()
    print(json.dumps(status, indent=2))
    
    print("\n🔄 Running Development Cycle:")
    test_plan = {
        "features": [
            {"name": "user_auth", "file": "auth.py"},
            {"name": "data_model", "file": "models.py"},
        ],
        "functions": [
            {"name": "calculate", "params": ["a", "b"], "description": "Calculate sum"},
            {"name": "validate", "params": ["data"], "description": "Validate input"},
        ],
    }
    
    results = org.run_development_cycle(test_plan)
    print(f"\n✅ Success: {results['success']}")


if __name__ == "__main__":
    main()
