#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright 2026 agentic-OS Contributors

"""
UNUSED CODE TEMPLATES - Archive
==============================
This file contains CODE TEMPLATES that were in omega_gan.py but never used.
Kept for reference - DO NOT DELETE unless sure.

These templates were designed for the CodeGenerator but were never 
instantiated - the generator uses dynamic code generation instead.

STATUS: DEPRECATED - Keep for reference only
"""

# ============================================================
# TEMPLATE 1: Secure Chat (Zero-Knowledge)
# ============================================================
# This was CODE_TEMPLATES["secure_chat"] in omega_gan.py
# Never used - kept for reference

SECURE_CHAT_TEMPLATE = '''#!/usr/bin/env python3
"""
Zero-Knowledge, Zero-Trust, Zero-Identifier Secure Chat Server
Generated by OMEGA-CODE Agentic-OS
{goal}
"""

import asyncio
import hashlib
import base64
import secrets
import time
from typing import Dict, Set, Optional, Tuple
from dataclasses import dataclass, field
from collections import defaultdict
import os

class ZeroKnowledgeCrypto:
    """Client-side encryption - server NEVER sees plaintext or keys."""
    
    @staticmethod
    def derive_key(password: str, salt: bytes) -> bytes:
        return hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 100000)
    
    @staticmethod
    def generate_keypair() -> Tuple[bytes, bytes]:
        private_key = secrets.token_bytes(32)
        public_key = hashlib.sha256(private_key).digest()
        return private_key, public_key
    
    @staticmethod
    def encrypt_message(message: str, key: bytes) -> Tuple[bytes, bytes]:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        nonce = secrets.token_bytes(12)
        aesgcm = AESGCM(key)
        ciphertext = aesgcm.encrypt(nonce, message.encode(), None)
        return nonce + ciphertext
    
    @staticmethod
    def decrypt_message(encrypted: bytes, key: bytes) -> str:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        nonce = encrypted[:12]
        ciphertext = encrypted[12:]
        aesgcm = AESGCM(key)
        return aesgcm.decrypt(nonce, ciphertext, None).decode()
    
    @staticmethod
    def hash_identifier(data: str) -> str:
        return hashlib.sha256(data.encode()).hexdigest()[:32]
    
    @staticmethod
    def generate_session_token() -> str:
        return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()

# ... (rest of secure chat implementation)
# NOTE: This template was never used
'''

# ============================================================
# TEMPLATE 2: Default Template
# ============================================================
DEFAULT_TEMPLATE = '''#!/usr/bin/env python3
"""
OMEGA Generated Code
Goal: {goal}
Constraints: {constraints_str}
"""

{imports}

{code_body}

if __name__ == "__main__":
    main()
'''

# ============================================================
# NOTE ON unused helper classes from omega_lsp_client.py
# ============================================================
# 
# The OmegaLSPClient class in omega_lsp_client.py had ~20+ methods:
# - start_servers()
# - stop_servers()  
# - get_completions()
# - get_definitions()
# - get_references()
# - get_hover()
# - get_code_actions()
# - format_document()
# - restart_servers()
# - And more...
#
# These were NEVER used because only SimpleLSPClient was instantiated.
# The full implementation remains in omega_lsp_client.py but is dead code.
#
# OPTION 1: Enable full LSP by changing self.lsp to OmegaLSPClient
# OPTION 2: Remove the dead code
# OPTION 3: Leave as-is for future LSP features
#
# Current status: DEAD_CODE (never instantiated)
#

# ============================================================
# NOTE ON FileAwareFeedbackLoop from omega_feedback_loop.py
# ============================================================
#
# class FileAwareFeedbackLoop(FeedbackLoop):
#     """Subclass with file-aware capabilities."""
#     def get_context_for_file(self, file_path: str) -> Dict:
#         ...
#
# This subclass was NEVER instantiated.
# Current status: DEAD_CODE
#


# ============================================================
# USAGE INSTRUCTIONS
# ============================================================
"""
To use any of these templates:

1. FOR TEMPLATES:
   from omega_error_classifier import SECURE_CHAT_TEMPLATE
   code = SECURE_CHAT_TEMPLATE.format(goal="Create secure chat")
   # Then compile with CodeGenerator

2. FOR LSP CLIENT:
   # In omega_codex.py, change:
   from omega_lsp_client import SimpleLSPClient  # current
   # to:
   from omega_lsp_client import OmegaLSPClient   # full features
   
   # Note: Requires LSP server (pylsp, pyright) to be installed

3. FOR FileAwareFeedbackLoop:
   # In omega_feedback_loop.py, change:
   loop = FeedbackLoop()        # current
   # to:
   loop = FileAwareFeedbackLoop()  # with file context
"""

# Keep this file for reference
# DO NOT DELETE - may be useful for future features